// Code generated by "stringer -type=CacheEntryStatus"; DO NOT EDIT.

package cache

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Live-0]
	_ = x[Timeout-1]
	_ = x[Dead-2]
	_ = x[Bot-3]
	_ = x[Ignore-4]
}

const _CacheEntryStatus_name = "LiveTimeoutDeadBotIgnore"

var _CacheEntryStatus_index = [...]uint8{0, 4, 11, 15, 18, 24}

func (i CacheEntryStatus) String() string {
	if i < 0 || i >= CacheEntryStatus(len(_CacheEntryStatus_index)-1) {
		return "CacheEntryStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CacheEntryStatus_name[_CacheEntryStatus_index[i]:_CacheEntryStatus_index[i+1]]
}
